workflows:
  react-native:
    name: simple-ios-todo
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "value here"
        XCODE_SCHEME: "value here"
        # iOS automatic code signing
        APP_STORE_CONNECT_ISSUER_ID: 123412341234
        APP_STORE_CONNECT_KEY_IDENTIFIER: 123412341234
        APP_STORE_CONNECT_PRIVATE_KEY: 123412341234
      xcode: latest
      node: latest
      npm: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:

            - name: Set up code signing settings on Xcode project
              script: xcode-project use-profiles
            - |
                # build iOS
                cd ios
                pod install
                xcode-project build-ipa --project "MyXcodeProject.xcodeproj" --scheme "MyScheme"
    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo 'Post-publish script'
